#
# Copyright 2022- IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#
dist: focal
sudo: false
language: scala
jdk: openjdk11

cache:
  directories:
    - "$HOME/.cache"
    - "$HOME/.m2"
    - "$HOME/.sbt"

before_install:
  - ./.travis/prepare-build.sh

jobs:
  include:
    - os: linux
      scala: 2.12.15
      env: SPARK_VERSION=3.2.1 SCALA_VERSION=2.12.15
    - os: linux
      scala: 2.13.5
      env: SPARK_VERSION=3.2.1 SCALA_VERSION=2.13.5
    - os: linux
      scala: 2.12.15
      env: SPARK_VERSION=3.3.0 SCALA_VERSION=2.12.15
    - os: linux
      scala: 2.13.8
      env: SPARK_VERSION=3.3.0 SCALA_VERSION=2.13.8

script:
  - sbt package
  - ls target/scala-*/*.jar

notifications:
  email: false

